### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by hmaarrfk** [nmikhailov/Validity90#22]
Hey,

Cool work. I have a 138a:0091 Validity Sensors, Inc. 

If you give me some instructions on how to sniff I would be glad to help see if I can dump anything.

Otherwise, I found a few missing dependencies for prototype

```
gnutls-devel
glib2-devel
```

Hope this helps

**Comment by nmikhailov** [comment]
Dependencies info updated.

**Comment by nmikhailov** [comment]
Out of scope, check out this project - https://github.com/hmaarrfk/Validity91
