### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by yerbestpal** [nmikhailov/Validity90#59]
This seems promising but not so active. Is it dead? Thanks.

**Comment by jontis** [comment]
https://gitter.im/Validity90/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by esc** [comment]
Ping @nmikhailov are you still around?

**Comment by nmikhailov** [comment]
Its not dead. I am sorry, I will try to resume my work on it asap.  :crying_cat_face:

**Comment by jontis** [comment]
Or, if you are very tight on time, maybe a partner could share some responsibility to allow the repo to go forward? No, that's not me ;-)

**Comment by MartinX3** [comment]
@nmikhailov will you mainline the code into the ubuntu repo? :)
T460p sensor works and I don't get the Ubuntu updates for the lib or I will loose my fingerprint :(

**Comment by esc** [comment]
@nmikhailov no worries, just rest assured that the community has your back, in case you need anything! I certainly appreciate the work you have been doing to bring a fingerprint scanner to my thinkpads!

**Comment by chopin1998** [comment]
i have a t480s, with a usb scanner: 06cb:009a Synaptics, Inc. 

if some test i can do, let me know.
