### ISSUE TITLE
What about 27c6:5301 model ?

### ISSUE THREAD

**Issue by TommyPujol06** [nmikhailov/Validity90#61]
I have a Goodix device 27c6:5301 would it work ?

Thank you.

**Comment by TommyPujol06** [comment]
Hi, @nmikhailov 

Do you know it or this project is abandoned ?

**Comment by parkerlreed** [comment]
Do a search https://github.com/hmaarrfk/Validity91/issues/5#issuecomment-378168229

Goodix is completely unrelated to Validity.

**Comment by TommyPujol06** [comment]
Ok, Thanks
